<?php

function simple_contact_form_alter(&$form, &$form_state, $form_id) {
// print '<pre>';
// print_r($form);
// print '</pre>';
  if($form_id == 'contact_site_form') {
    //Hidden with the access set to 0 for no access.
    $form['copy']['#access'] = 0;
    $form['subject']['#access'] = 0;

    //Settings default values
    $form['copy']['#default_value'] = 1;
    $form['subject']['#default_value'] = t('Feedback');
  }

  if($form_id == 'node_type_form') {
    $form['display']['node_submitted']['#default_value'] = 0;
  }
}
